title: Sharon Chuang # your name (or website title) here
logo: "/images/profile.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst Intern @ CGHPI
  <br>
  Student of Data Science for Public Policy @ Georgetown’s Mccourt School of public policy
  <br>
  <br>
  <a href="https://www.linkedin.com/in/shiawshiuan-sharon-chuang/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
